blog/urls.py
from . import views
from django.urls import path
from .views import PostListView, AddPostView, UpdatePostView, PostDetail, DeletePostView, UpdateCommentView, DeleteCommentView, custom_handler404, custom_handler500, custom_login


# Urls for the project
urlpatterns = [
    path('', views.PostList.as_view(), name='home'),
    path('add_post/', AddPostView.as_view(), name='add_post'),
    path('post_list/', PostListView.as_view(), name='post_list'),
    path('custom-login/', custom_login, name='custom_login'),
    path('article/edit/<int:pk>/', UpdatePostView.as_view(), name='update_post'),
    path('article/edit/<int:pk>/delete', DeletePostView.as_view(), name='delete_post'),
    path('<slug:slug>/', views.PostDetail.as_view(), name='post_detail'),
    path('like/<slug:slug>', views.PostLike.as_view(), name='post_like'),
    path('article/edit/<int:pk>/remove', DeleteCommentView.as_view(), name='comment_delete'),
    path('article/edit/<int:pk>/update', UpdateCommentView.as_view(), name='update_comment'),
]


handler404 = custom_handler404
handler500 = custom_handler500


# The code in this file is inspired from:
# My own previous projects and knowledge
# Code Institute, I think therefore i blog project
# Youtube series Django Tutorial by [Net Ninja](https://www.youtube.com/watch?v=n-FTlQ7Djqc&list=PL4cUxeGkcC9ib4HsrXEYpQnTOTZE1x0uc&index=1&ab_channel=NetNinja)
# Youtube series Python Django Tutorial by [Corey Schafer](https://www.youtube.com/watch?v=UmljXZIypDc&list=PL-osiE80TeTtoQCKZ03TU5fNfx2UY6U4p&index=1&ab_channel=CoreySchafer)
# Yoube Python Django Web Framework by [FreeCodeCamp](https://www.youtube.com/watch?v=F5mRW0jo-U4&ab_channel=freeCodeCamp.org)

mc_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls'), name='blog_urls'),
    path('summernote/', include('django_summernote.urls')),
    path('accounts/', include('allauth.urls')),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField
from django.urls import reverse
from django.utils.text import slugify


# Define choices for the status field
STATUS = ((0, "Draft"), (1, "Published"))


# Model representing a blog post
class Post(models.Model):
    title = models.CharField(max_length=150, unique=True) # Title of the post, must be unique
    body = models.TextField(default='') # Body of the post
    slug = models.SlugField(max_length=150, unique=True) # URL-friendly slug, must be unique
    author = models.ForeignKey( # Author of the post, linked to the User model
        User, on_delete=models.CASCADE, related_name="blog_posts"
    )
    featured_image = CloudinaryField('image', default='placeholder') # Featured image for the post, stored using Cloudinary
    author_image = CloudinaryField('image', default='placeholder', blank=True, null=True) # Author's profile image, stored using Cloudinary, optional field
    excerpt = models.TextField(blank=True) # Excerpt of the post
    mc_brand_name = models.CharField(max_length=50, blank=True, null=True) # Motorcycle brand name
    mc_type_name = models.CharField(max_length=50, blank=True, null=True)  # Motorcycle type
    updated_on = models.DateTimeField(auto_now=True) # Timestamp of the last update
    created_on = models.DateTimeField(auto_now_add=True) # Timestamp of post creation
    status = models.IntegerField(choices=STATUS, default=1) # Status of the post (draft or published)
    likes = models.ManyToManyField( # Users who liked the post, many-to-many relationship
        User, related_name='blogpost_like', blank=True)

    # Meta class to define additional settings
    class Meta:
        ordering = ["-created_on"]

    # Override the save method to auto-generate slug from title if not provided
    def save(self, *args, **kwargs):

        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    # String representation of the model
    def __str__(self):
        return self.title

    # Method to count the number of likes for a post
    def number_of_likes(self):
        return self.likes.count()

    # Method to get the absolute URL of a post
    def get_absolute_url(self):
        return reverse('home')


# Model representing a comment on a blog post
class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, # The post the comment is related to
                             related_name="comments")
    name = models.CharField(max_length=80) # Name of the person who commented
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None) # User who commented, linked to the User model
    email = models.EmailField() # Email of the person who commented
    body = models.TextField() # Body of the comment
    created_on = models.DateTimeField(auto_now_add=True) # Timestamp of comment creation
    approved = models.BooleanField(default=True) # Approval status of the comment

    # Meta class to define additional settings
    class Meta:
        ordering = ["created_on"] # Order comments by creation date in ascending order

    # String representation of the model
    def __str__(self):
        return f"Comment {self.body} by {self.name}"


# The code in this file is inspired from:
# My own previous projects and knowledge
# Code Institute, I think therefore i blog project
# Youtube series Django Tutorial by [Net Ninja](https://www.youtube.com/watch?v=n-FTlQ7Djqc&list=PL4cUxeGkcC9ib4HsrXEYpQnTOTZE1x0uc&index=1&ab_channel=NetNinja)
# Youtube series Python Django Tutorial by [Corey Schafer](https://www.youtube.com/watch?v=UmljXZIypDc&list=PL-osiE80TeTtoQCKZ03TU5fNfx2UY6U4p&index=1&ab_channel=CoreySchafer)
# Yoube Python Django Web Framework by [FreeCodeCamp](https://www.youtube.com/watch?v=F5mRW0jo-U4&ab_channel=freeCodeCamp.org)

blog/forms.py
from .models import Comment, Post
from django import forms


# Form for the Comment model
class CommentForm(forms.ModelForm):
    body = forms.CharField(widget=forms.Textarea, label='') # Define the body field as a CharField with a Textarea widget and no label
    class Meta: # Specify the model and fields to include in the form
        model = Comment
        fields = ('body',)


# Form for the Post model
class PostForm(forms.ModelForm):
    class Meta: # Specify the model and fields to include in the form
        model = Post
        fields = ['title', 'body', 'mc_brand_name', 'mc_type_name', 'featured_image', 'author_image',]

    # Custom initialization method to set field requirements
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['title'].required = True
        self.fields['body'].required = True
        self.fields['featured_image'].required = False
        self.fields['author_image'].required = False


# The code in this file is inspired from:
# My own previous projects and knowledge
# Code Institute, I think therefore i blog project
# Python Django Web Framework (https://www.djangoproject.com/start/overview/)
# Youtube Django Tutorial by [Freecode camp](https://www.youtube.com/watch?v=F5mRW0jo-U4)
# Youtube series Django Tutorial by [Net Ninja](https://www.youtube.com/watch?v=n-FTlQ7Djqc&list=PL4cUxeGkcC9ib4HsrXEYpQnTOTZE1x0uc&index=1&ab_channel=NetNinja)
# Youtube series Python Django Tutorial by [Corey Schafer](https://www.youtube.com/watch?v=UmljXZIypDc&list=PL-osiE80TeTtoQCKZ03TU5fNfx2UY6U4p&index=1&ab_channel=CoreySchafer)
# Yoube Python Django Web Framework by [FreeCodeCamp](https://www.youtube.com/watch?v=F5mRW0jo-U4&ab_channel=freeCodeCamp.org)

templates/add_post.html
<!-- Extends the base template -->
{% extends 'base.html' %}
<!-- Main content block -->
{% block content %}

<!-- Container for the form content -->
<div class="container">
  <div class="row justify-content-center">
    <!-- Form column centered on the page -->
    <div class="col-md-8">
      <h1 class="text-center">Add a post</h1>
      <!-- Form for adding a post -->
      <form method="POST" enctype="multipart/form-data">
        <!-- CSRF protection token -->
        {% csrf_token %}
        <!-- Form group for title input -->
        <div class="form-group row">
          <label for="id_title" class="col-sm-3 col-form-label">Title:</label>
          <div class="col-sm-5">
            <!-- Title input field -->
            {{ form.title }}
            <!-- Display errors for title input if any -->
            {% if form.title.errors %}
              <div class="text-danger">
                {{ form.title.errors }}
              </div>
            {% endif %}
          </div>
        </div>
        <!-- Form group for body input -->
        <div class="form-group row">
          <label id="text_input" for="id_body" class="col-sm-3 col-form-label">Text:</label>
          <div class="col-sm-5">
            <!-- Body input field -->
            {{ form.body }}
            <!-- Display errors for body input if any -->
            {% if form.body.errors %}
              <div class="text-danger">
                {{ form.body.errors }}
              </div>
            {% endif %}
          </div>
        </div>
        <!-- Form group for mc brand name input -->
        <div class="form-group row">
          <label for="id_mc_brand_name" class="col-sm-3 col-form-label">MC Brand Name:(optional)</label>
          <div class="col-sm-5">
            <!-- MC Brand Name input field -->
            {{ form.mc_brand_name }}
            <!-- Display errors for mc brand name input if any -->
            {% if form.mc_brand_name.errors %}
              <div class="text-danger">
                {{ form.mc_brand_name.errors }}
              </div>
            {% endif %}
          </div>
        </div>
        <!-- Form group for mc type name input -->
        <div class="form-group row">
          <label for="id_mc_type_name" class="col-sm-3 col-form-label">MC Type Name:(optional)</label>
          <div class="col-sm-5">
            <!-- MC Type Name input field -->
            {{ form.mc_type_name }}
            <!-- Display errors for mc type name input if any -->
            {% if form.mc_type_name.errors %}
              <div class="text-danger">
                {{ form.mc_type_name.errors }}
              </div>
            {% endif %}
          </div>
        </div>
        <!-- Form group for featured image input -->
        <div class="form-group row">
          <label for="id_featured_image" class="col-sm-3 col-form-label">Post Image:(optional)</label>
          <div class="col-sm-5">
            <!-- Featured image input field -->
            <input type="file" style="margin-bottom: 20px;" id="id_featured_image" name="featured_image">
            <!-- Display errors for featured image input if any -->
            {% if form.featured_image.errors %}
              <div class="text-danger">
                {{ form.featured_image.errors }}
              </div>
            {% endif %}
          </div>
        </div>
        <!-- Form group for author image input -->
        <div class="form-group row">
          <label for="id_author_image" class="col-sm-3 col-form-label">Profile Image:(optional)</label>
          <div class="col-sm-5">
            <!-- Author image input field -->
            <input type="file" id="id_author_image" name="author_image">
            <!-- Display errors for author image input if any -->
            {% if form.author_image.errors %}
              <div class="text-danger">
                {{ form.author_image.errors }}
              </div>
            {% endif %}
          </div>
        </div>
        <!-- Form group for submit button -->
        <div class="form-group row">
          <div class="col-sm-5 offset-sm-3">
            <!-- Submit button for the form -->
            <button style="margin-top: 20px;" class="btn btn-signup right btn-lg" type="submit">Post</button>
          </div>
        </div>
      </form>
      <!-- Display non-field errors if any -->
      {% if form.non_field_errors %}
        <div class="alert alert-danger">
          {{ form.non_field_errors }}
        </div>
      {% endif %}
    </div>
  </div>
</div>

<!-- End of the content block -->
{% endblock %}

</body>
</html>


<!-- The code in this file is inspired from:
My own previous projects and knowledge
Code Institute, I think therefore i blog project
Python Django Web Framework (https://www.djangoproject.com/start/overview/)
Youtube Django Tutorial by [Freecode camp](https://www.youtube.com/watch?v=F5mRW0jo-U4)
Youtube series Django Tutorial by [Net Ninja](https://www.youtube.com/watch?v=n-FTlQ7Djqc&list=PL4cUxeGkcC9ib4HsrXEYpQnTOTZE1x0uc&index=1&ab_channel=NetNinja)
Youtube series Python Django Tutorial by [Corey Schafer](https://www.youtube.com/watch?v=UmljXZIypDc&list=PL-osiE80TeTtoQCKZ03TU5fNfx2UY6U4p&index=1&ab_channel=CoreySchafer)
Yoube Python Django Web Framework by [FreeCodeCamp](https://www.youtube.com/watch?v=F5mRW0jo-U4&ab_channel=freeCodeCamp.org) -->

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en" class="h-100">
<head>
    <title>Motorcycle Blog</title>
    <!-- Link to Fonts, bootstrap and stylesheets-->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous">
    </script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body class="d-flex flex-column h-100 main-bg">
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-white">
        <div class="container-fluid">
            <!-- Brand logo and name -->
            <a class="navbar-brand" href="{% url 'home' %}"><span class="brand">MOTORCYCLE<span
                        class="thin">|BLOG</span></span></a>
            <!-- Toggle button for collapsing the navbar on small screens -->
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText"
                aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <!-- Navbar links and options -->
            <div class="collapse navbar-collapse" id="navbarText">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
                    </li>
                    <!-- Conditional links based on user authentication status -->
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_logout' %}">Logout</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'post_list' %}">Posts</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'add_post' %}">Add a Post</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_signup' %}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_login' %}">Login</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    <!-- Container for displaying CRUD alert messages -->
    <div class="container">
        <div class="row">
            <div class="col-md-8 offset-md-2">
                {% for message in messages %}
                <div class="alert {{ message.tags }} alert-dismissible fade show" id="msg" role="alert">
                    {{ message | safe }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>

    <!-- Main content area -->
    <main class="flex-shrink-0 main-bg">
        {% block content %}
        {% endblock content %}
    </main>

    <!-- Footer -->
    <footer class="footer mt-auto py-3 dark-bg btn-lg">
        <p class="m-0 text-center text-white">FOLLOW ME:
            <a href="https://www.facebook.com/" target="_blank"><i class="fab fa-facebook-square ms-3"></i></a>
            <a href="https://twitter.com/" target="_blank"><i class="fab fa-twitter-square ms-3"></i></a>
            <a href="https://www.instagram.com/" target="_blank"><i class="fab fa-instagram-square ms-3"></i></a>
            <a href="https://www.youtube.com/" target="_blank"><i class="fab fa-youtube-square ms-3"></i></a>
        </p>
    </footer>

    <!-- JavaScript to automatically close alert messages after a delay -->
    <script>
        setTimeout(function () {
            let messages = document.getElementById('msg');
            let alert = new bootstrap.Alert(messages);
            alert.close();
        }, 2500);
    </script>
</body>
</html>


<!-- The code in this file is inspired from:
My own previous projects and knowledge
Code Institute, I think therefore i blog project
Python Django Web Framework (https://www.djangoproject.com/start/overview/)
Youtube Django Tutorial by [Freecode camp](https://www.youtube.com/watch?v=F5mRW0jo-U4)
Youtube series Django Tutorial by [Net Ninja](https://www.youtube.com/watch?v=n-FTlQ7Djqc&list=PL4cUxeGkcC9ib4HsrXEYpQnTOTZE1x0uc&index=1&ab_channel=NetNinja)
Youtube series Python Django Tutorial by [Corey Schafer](https://www.youtube.com/watch?v=UmljXZIypDc&list=PL-osiE80TeTtoQCKZ03TU5fNfx2UY6U4p&index=1&ab_channel=CoreySchafer)
Yoube Python Django Web Framework by [FreeCodeCamp](https://www.youtube.com/watch?v=F5mRW0jo-U4&ab_channel=freeCodeCamp.org) -->

templates/comment_delete.html
{% extends 'base.html' %} 
{% block content %}

<div class="container">
  <h1 style="margin-top: 25px;">Delete comment</h1>
  <div class="form-group">
    <form method="POST">
      {% csrf_token %}
      <h5 style="margin-top: 25px;">Are you sure?</h5>
      <button class="btn btn-signup right btn-lg" style="margin-top: 25px;" type="submit">Delete</button>
    </form>
  </div>
</div>

{% endblock %}


<!-- The code in this file is inspired from:
My own previous projects and knowledge
Code Institute, I think therefore i blog project
Python Django Web Framework (https://www.djangoproject.com/start/overview/)
Youtube Django Tutorial by [Freecode camp](https://www.youtube.com/watch?v=F5mRW0jo-U4)
Youtube series Django Tutorial by [Net Ninja](https://www.youtube.com/watch?v=n-FTlQ7Djqc&list=PL4cUxeGkcC9ib4HsrXEYpQnTOTZE1x0uc&index=1&ab_channel=NetNinja)
Youtube series Python Django Tutorial by [Corey Schafer](https://www.youtube.com/watch?v=UmljXZIypDc&list=PL-osiE80TeTtoQCKZ03TU5fNfx2UY6U4p&index=1&ab_channel=CoreySchafer)
Yoube Python Django Web Framework by [FreeCodeCamp](https://www.youtube.com/watch?v=F5mRW0jo-U4&ab_channel=freeCodeCamp.org) -->

templates/delete_post.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
  <h1 style="margin-bottom: 25px; margin-top: 25px;">Delete post</h1>
  <h3>Delete: {{ post.title }}</h3>
  <div class="form-group">
    <form method="POST">
      {% csrf_token %}
      <h5 style="margin-top: 25px;">Are you sure...?</h5>
      <button class="btn btn-signup right btn-lg" style="margin-top: 25px;" type="submit">Delete</button>
    </form>
  </div>
</div>

{% endblock %}


<!-- The code in this file is inspired from:
My own previous projects and knowledge
Code Institute, I think therefore i blog project
Python Django Web Framework (https://www.djangoproject.com/start/overview/)
Youtube Django Tutorial by [Freecode camp](https://www.youtube.com/watch?v=F5mRW0jo-U4)
Youtube series Django Tutorial by [Net Ninja](https://www.youtube.com/watch?v=n-FTlQ7Djqc&list=PL4cUxeGkcC9ib4HsrXEYpQnTOTZE1x0uc&index=1&ab_channel=NetNinja)
Youtube series Python Django Tutorial by [Corey Schafer](https://www.youtube.com/watch?v=UmljXZIypDc&list=PL-osiE80TeTtoQCKZ03TU5fNfx2UY6U4p&index=1&ab_channel=CoreySchafer)
Yoube Python Django Web Framework by [FreeCodeCamp](https://www.youtube.com/watch?v=F5mRW0jo-U4&ab_channel=freeCodeCamp.org) -->

templates/index.html
{% extends "base.html" %} 
{% load static %}
{% block content %}

<div class="container">
        <div class="text-block">
        <h2>Motorcycle Adventures</h2>
        <p>Welcome to my motorcycle diary, where every turn of the wheel unfolds a new adventure. 
            Here, I invite you to join me on the open road as I share the stories of my personal bike 
            and the unforgettable journeys it has taken me on. Through vivid imagery and heartfelt narration, 
            I'll take you on a ride through the scenic landscapes, hidden gems, and cherished moments 
            that have defined my two-wheeled escapades.<br><br>
            
            From the gleaming chrome of my trusted steed 
            to the breathtaking vistas that unfold before me, each post is a testament to the bond between 
            rider and machine, and the unbridled freedom that comes with it. So, grab your helmet, saddle up, 
            and let's embark on a thrilling ride through the twists and turns of my motorcycle adventures.</p>
        </div>
    <div class="image-block"></div>
</div>

{% endblock %}


<!-- The code in this file is inspired from:
My own previous projects and knowledge
Code Institute, I think therefore i blog project
Python Django Web Framework (https://www.djangoproject.com/start/overview/)
Youtube Django Tutorial by [Freecode camp](https://www.youtube.com/watch?v=F5mRW0jo-U4)
Youtube series Django Tutorial by [Net Ninja](https://www.youtube.com/watch?v=n-FTlQ7Djqc&list=PL4cUxeGkcC9ib4HsrXEYpQnTOTZE1x0uc&index=1&ab_channel=NetNinja)
Youtube series Python Django Tutorial by [Corey Schafer](https://www.youtube.com/watch?v=UmljXZIypDc&list=PL-osiE80TeTtoQCKZ03TU5fNfx2UY6U4p&index=1&ab_channel=CoreySchafer)
Yoube Python Django Web Framework by [FreeCodeCamp](https://www.youtube.com/watch?v=F5mRW0jo-U4&ab_channel=freeCodeCamp.org) -->

templates/update_post.html
{% extends 'base.html' %}
{% block content %}

<!-- Container for the edit post form -->
<div class="container">
  <!-- Row to center the form -->
 <div class="row justify-content-center">
   <!-- Column for the form -->
   <div class="col-md-8">
     <!-- Heading for the form -->
     <h1 class="text-center">Edit your post</h1>
     <!-- Form for editing the post -->
     <form method="POST" enctype="multipart/form-data">
       {% csrf_token %}
       <!-- Form group for the post title -->
       <div class="form-group row">
         <label for="id_title" class="col-sm-3 col-form-label">Title:</label>
         <div class="col-sm-5">
           <!-- Input field for the post title -->
           {{ form.title }}
           <!-- Display errors for title input if any -->
           {% if form.title.errors %}
             <div class="text-danger">
               {{ form.title.errors }}
             </div>
           {% endif %}
         </div>
       </div>
       <!-- Form group for the post body -->
       <div class="form-group row">
         <label id="text_input" for="id_body" class="col-sm-3 col-form-label">Text:</label>
         <div class="col-sm-5">
           <!-- Text area for the post body -->
           {{ form.body }}
           <!-- Display errors for body input if any -->
           {% if form.body.errors %}
             <div class="text-danger">
               {{ form.body.errors }}
             </div>
           {% endif %}
         </div>
       </div>
       <!-- Form group for mc brand name input -->
       <div class="form-group row">
         <label for="id_mc_brand_name" class="col-sm-3 col-form-label">MC Brand Name:(optional)</label>
         <div class="col-sm-5">
           <!-- MC Brand Name input field -->
           {{ form.mc_brand_name }}
           <!-- Display errors for mc brand name input if any -->
           {% if form.mc_brand_name.errors %}
             <div class="text-danger">
               {{ form.mc_brand_name.errors }}
             </div>
           {% endif %}
         </div>
       </div>
       <!-- Form group for mc type name input -->
       <div class="form-group row">
         <label for="id_mc_type_name" class="col-sm-3 col-form-label">MC Type Name:(optional)</label>
         <div class="col-sm-5">
           <!-- MC Type Name input field -->
           {{ form.mc_type_name }}
           <!-- Display errors for mc type name input if any -->
           {% if form.mc_type_name.errors %}
             <div class="text-danger">
               {{ form.mc_type_name.errors }}
             </div>
           {% endif %}
         </div>
       </div>
       <!-- Form group for the post image -->
       <div class="form-group row">
         <label for="id_featured_image" class="col-sm-3 col-form-label">Post Image:(optional)</label>
         <div class="col-sm-5">
           <!-- Input field for uploading the post image -->
           <input type="file" style="margin-bottom: 20px;" id="id_featured_image" name="featured_image">
           <!-- Display errors for featured image input if any -->
           {% if form.featured_image.errors %}
             <div class="text-danger">
               {{ form.featured_image.errors }}
             </div>
           {% endif %}
         </div>
       </div>
       <!-- Form group for the author image -->
       <div class="form-group row">
         <label for="id_author_image" class="col-sm-3 col-form-label">Profile Image:(optional)</label>
         <div class="col-sm-5">
           <!-- Input field for uploading the author image -->
           <input type="file" id="id_author_image" name="author_image">
           <!-- Display errors for author image input if any -->
           {% if form.author_image.errors %}
             <div class="text-danger">
               {{ form.author_image.errors }}
             </div>
           {% endif %}
         </div>
       </div>
       <!-- Button to submit the form -->
       <div class="form-group row">
         <div class="col-sm-5 offset-sm-3">
           <button style="margin-top: 20px;" class="btn btn-signup right btn-lg" type="submit">Post</button>
         </div>
       </div>
     </form>
   </div>
 </div>
</div>

{% endblock %}


<!-- The code in this file is inspired from:
My own previous projects and knowledge
Code Institute, I think therefore i blog project
Python Django Web Framework (https://www.djangoproject.com/start/overview/)
Youtube Django Tutorial by [Freecode camp](https://www.youtube.com/watch?v=F5mRW0jo-U4)
Youtube series Django Tutorial by [Net Ninja](https://www.youtube.com/watch?v=n-FTlQ7Djqc&list=PL4cUxeGkcC9ib4HsrXEYpQnTOTZE1x0uc&index=1&ab_channel=NetNinja)
Youtube series Python Django Tutorial by [Corey Schafer](https://www.youtube.com/watch?v=UmljXZIypDc&list=PL-osiE80TeTtoQCKZ03TU5fNfx2UY6U4p&index=1&ab_channel=CoreySchafer)
Yoube Python Django Web Framework by [FreeCodeCamp](https://www.youtube.com/watch?v=F5mRW0jo-U4&ab_channel=freeCodeCamp.org) -->